bpfmetaver: "v1"
kind: "bpf"
bpfmetadata:
  name: bpflock
bpfspec:
  programs:
    - name: execsnoop
      description: "Trace process exec()"
      doc: https://github.com/linux-lock/bpflock/blob/main/docs/system-and-application-tracing.md#trace-application-execution
      args:
        - --exec-snoop=none
    - name: kimglock
      description: "Restrict both direct and indirect modification to a running kernel image" 
      doc: https://github.com/linux-lock/bpflock/blob/main/docs/memory-protections.md#1-kernel-image-lock-down
      command: kimglock
      args:
        - --profile=allow
    - name: kmodlock
      description: "Restrict kernel module operations on modular kernels"
      doc: https://github.com/linux-lock/bpflock/blob/main/docs/memory-protections.md#2-kernel-modules-protections
      command: kmodlock
      args:
        - --profile=allow
    - name: bpfrestrict
      description: "Restrict access to the bpf() system call"
      doc: https://github.com/linux-lock/bpflock/blob/main/docs/memory-protections.md#3-bpf-protection
      command: bpfrestrict
      args:
        - --profile=allow
    - name: filelesslock
      description: "Restrict fileless binary execution from memory"
      doc: https://github.com/linux-lock/bpflock/tree/main/docs/process-protections.md#fileless-memory-execution
      command: filelesslock
      args:
        - --profile=allow
