// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BpfProgram bpf program
//
// swagger:model BpfProgram
type BpfProgram struct {

	// Command line arguments passed to the bpf program launcher
	Args []string `json:"args"`

	// Command name of the bpf program launcher
	Command string `json:"command,omitempty"`

	// Description of the bpf program
	Description string `json:"description,omitempty"`

	// Name of bpf program
	Name string `json:"name,omitempty"`

	// Launch priority of the bpf program
	Priority int32 `json:"priority,omitempty"`
}

// Validate validates this bpf program
func (m *BpfProgram) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bpf program based on context it is used
func (m *BpfProgram) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BpfProgram) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BpfProgram) UnmarshalBinary(b []byte) error {
	var res BpfProgram
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
