// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BpfMetadata bpf metadata
//
// swagger:model BpfMetadata
type BpfMetadata struct {

	// The name of the bpf program launcher and manager
	Name string `json:"name,omitempty"`
}

// Validate validates this bpf metadata
func (m *BpfMetadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bpf metadata based on context it is used
func (m *BpfMetadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BpfMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BpfMetadata) UnmarshalBinary(b []byte) error {
	var res BpfMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
