// Code generated by go-swagger; DO NOT EDIT.

// Package restapi bpflock API
//
//  bpflock
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: v1beta
//  License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
